### ISSUE TITLE
Trained model?

### ISSUE THREAD

**Issue by Ken2yLiu** [pythonuser200/LLNet#1]
Hi,

Where can I find the trained model?

Thx

**Comment by pythonuser200** [comment]
I will place it in our Laboratory's dropbox folder and share the link via the repository in a bit. I am currently busy. Thanks for your interest.

Adedotun

**Comment by Ken2yLiu** [comment]
👍

**Comment by Ken2yLiu** [comment]
👍 
Looking forward to your update :-)

**Comment by Wisgon** [comment]
Looking forward to your model,too

**Comment by pythonuser200** [comment]
Sample model added.
